### ISSUE TITLE
Crear componente NewsCard (Por defecto)

### ISSUE THREAD

**Issue by RubisRage** [deii-ulpgc-tecnologia/deii-frontend#5]
# Creación del componente NewsCard (Default)

Vendría a ser una miniatura de la noticia. Muestra el título, autor, etiquetas, etc.

Este componente tiene dos estado, cuando el ratón está sobre él (Hover) y cuando no (Default). En esta issue se pide que se implemente únicamente el estado por defecto, cuyo diseño se muestra a continuación.

<img width="495" alt="Captura de pantalla 2023-07-19 a las 11 22 42" src="https://github.com/deii-ulpgc-tecnologia/deii-frontend/assets/30629957/03175eaa-a5c0-42f6-a580-111f0b97f079">

## Enlace al Figma

En la pestaña Designing de la página de noticias de Figma puedes observar en mayor detalle el componente a implementar.

[Figma - Noticias](https://www.figma.com/file/z5w0rISAoNngeGPZ3QjOom/Noticias?type=design&node-id=1%3A7&mode=design&t=EE050PR6OXEbYQjS-1)

## Realización de la tarea

Para llevar a cabo esta tarea solo debes modificar el fichero `src/dcomponents/news/NewsCard/index.tsx`. Dentro de este fichero existen dos subcomponentes `NewsCardHover` y `NewsCardDefault`, este último es el que tendrás que crear. Toda la información necesaria de la noticia se pasa al componente a través de un prop que se denomina obj en el código y es de tipo `News`, puedes aprender más sobre este tipo y sus contenidos accediendo al fichero `src/types/db/news.ts`.

## Requisitos de validación

- [ ] Se hace uso de la librería **chakraui** para llevar a cabo la implementación. [Más información](https://chakra-ui.com/docs/components)
- [ ] El componente debe coincidir visualmente con el diseño proporcionado.
- [ ] El componente debe ser responsive y funcionar correctamente en dispositivos móviles.
- [ ] Todas las propiedades deben mostrarse correctamente en el componente.
- [ ] Al hacer clic en el componente, debe redirigir a la ruta `/news/:id` (La id de la noticia, es decir, `obj.id`). Los cambios relacionados con esta sección deben aplicarse sobre el componente NewsCard, de forma que la redirección se aplique tanto si se está mostrando el estado por defecto o el Hover.

## Resolución de dudas y entrega de tareas

- Sube tu rama haciendo uso de `git push`
- Navega hasta la página del issue en GitHub.
- Agrega un comentario nuevo haciendo clic en el botón "Comment" (Comentar).
- Menciona al encargado del proyecto utilizando la sintaxis `@nombredeusuario` y adjunta tu **duda** o **solicitud de revisión**.
- Escribe cualquier mensaje adicional que desees transmitir al encargado del proyecto, explicando claramente que deseas que revise el issue.
- Haz clic en el botón "Comment" (Comentar) para publicar tu comentario.

### 1. Prepara el entorno de desarrollo. 

Utiliza la [guía de configuración](https://github.com/deii-ulpgc-tecnologia/documentation/blob/main/introductory-guides/setup-guide.md) para preparar el entorno de desarrollo si no lo has hecho ya. 

### 2. Clonar el repositorio de GitHub

Existen dos formas de descargar y subir cambios a github: HTTP y SSH. Nosotros recomendamos el uso de SSH y dejamos [aquí](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) una guía de cómo configurarlo. Si por el contrario decides utilzar HTTP necesitarás configurar un [token](https://docs.github.com/es/enterprise-cloud@latest/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) de github para poder subir tus cambios.  

Después de considerar esto puedes utilizar alguna de las dos siguientes órdenes para clonar (Crear una copia en tú máquina) del repositorio.

Si usas HTTP:
```
git clone https://github.com/deii-ulpgc-tecnologia/deii-frontend.git
```

Si tienes configurado el token SSH:
```
git clone git@github.com:deii-ulpgc-tecnologia/deii-frontend.git
```

### 3. Arrancar el entorno de desarrollo

Desde una terminal y dentro del proyecto, es conveniente que instales las dependencias del proyecto para que tu editor te pueda autocompletar código y encontrar errores haciendo uso del siguiente comando: 

```
npm install
```

Posteriormente es importante que arranques los distintos servicios que se utilizarán durante el desarrollo. Para ello basta con ejecutar la siguiente orden: 

```
docker compose up 
```

Esto inicializará 3 servicios distintos: 

**Página web de desarrollo**
- Localización: [localhost:3000](http://localhost:3000)
- Permite ver los cambios realizados en tiempo real sobre la página de la delegación.

**Storybook**
- Localización: [localhost:8008](http://localhost:8008)
- Permite ver los cambios realizados en tiempo real sobre un **componente en particular** además de cambiar los parámetros que recibe para asegurarse de que funciona adecuadamente.

**Base de datos de desarrollo**
- Localización: [localhost:8090/_/](http://localhost:8090/_/)
- Almacena información de ejemplo que se utilizará durante el desarrollo de la página. Puesto que cada desarrollador tiene su copia propia de esta base de datos y los cambios se revierten cada vez que se apaga el servicio te invitamos a que la modifiques como consideres apropiado. Para poder acceder necesitarás los siguientes credenciales:
    - email: dev@deii.com
    - pass: devpassword

Familiarizate con estos servicios que te serán de gran ayuda.

### 4. Cambiar a la branch del issue

Ahora que ya estás listo para empezar a trabajar es conveniente que te crees tu propia rama independiente dónde empezar a trabajar. Para ello basta con que ejecutes los siguientes comandos.

```
git checkout dev
git pull 
git checkout -b @feature/[nombre-del-componente]
```

**Comment by PinkBlure** [comment]
@josericardopenase @RubisRage Solicitud de revisión del último push.

**Comment by PinkBlure** [comment]
@RubisRage @josericardopenase Completo
